### ISSUE TITLE
Feature Request: Add custom fields to define index and error documents

### ISSUE THREAD

**Issue by groteworld** [fernando-mc/serverless-finch#16]
It would be nice to be able to define the following config so that a single page application could set them both to 'index.html'. The following config should be defaults if not provided, to not break current implementations.

```yml
custom:
  client:
    indexDocument: 'index.html'
    errorDocument: 'error.html'
```
