### ISSUE TITLE
TypeError: e.join is not a function on client deploy.

### ISSUE THREAD

**Issue by JexPY** [fernando-mc/serverless-finch#187]
**On command**
```sh
serverless client deploy
```
**Throws:**
```js
TypeError: e.join is not a function
    at Client._validateConfig (/home/runner/MonthlyHeftyArray/node_modules/serverless-finch/lib/plugin.js:88:76)
    at Client._removeDeployedResources (/home/runner/MonthlyHeftyArray/node_modules/serverless-finch/lib/plugin.js:96:17)
    at client:remove:remove (/home/runner/MonthlyHeftyArray/node_modules/serverless-finch/lib/plugin.js:79:21)
    at PluginManager.runHooks (/home/runner/MonthlyHeftyArray/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/home/runner/MonthlyHeftyArray/node_modules/serverless/lib/classes/plugin-manager.js:564:20)
    at async PluginManager.run (/home/runner/MonthlyHeftyArray/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/home/runner/MonthlyHeftyArray/node_modules/serverless/lib/serverless.js:179:5)
    at async /home/runner/MonthlyHeftyArray/node_modules/serverless/scripts/serverless.js:819:9
```

### Works as expected:
```sh
serverless deploy
```

**Configuration**
The `serverless.yml` that produces the bug.

```yml
service: serverless-form

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ${file(../configuration.json):lambdaLocation}

functions:
  serverlessForm:
    handler: handler.lambda_handler
    role: ${file(../configuration.json):lambdaRole}
    environment:
      DYNAMO_DB_TABLE: ${file(../configuration.json):dynamoDBtable}

plugins:
  - serverless-finch

custom:
  finch:
    bucketName: ${file(../configuration.json):s3ForStaticBucket}
    distributionFolder: ../static-web
    indexDocument: index.html
    region: ${file(../configuration.json):s3ForStaticRegion}
```
**Operating system (please complete the following information):**

Environment: linux, node 16.18.1, framework 3.30.1 (local), plugin 6.2.3, SDK 4.3.2, serverless-finch 4.0.2.

** Question? **
Is it caused by `distributionFolder: ../static-web` ?
