### ISSUE TITLE
Feature suggestion: Allow user to specify metadata for uploaded files

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#24]
S3 bucket hosting allows you to set HTTP headers for responses to incoming requests via "Metadata" for each object in the bucket. It would be great to be able to specify these through the options in `serverless.yml`.

A specific use case for this would be for setting Cache-Control headers, which are particularly important for making sure that browsers don't cache files on your site that may change frequently.

I'm imagining this as an optional parameter in `serverless.yml` that could specify metadata for any specific file or folder as well as for the every object in the bucket. File-specific metadata would override folder-specific metadata, which would in turn override ALL_OBJECTS metadata.

```yaml
custom:
  client:
    ...
    objectMetadata:
        - specific-file-that-shouldnt-be-cached:
            - mdata-name: Cache-Control
              mdata-value: no-cache
            - mdata-name: Content-Language
              mdata-value: es-ES
        - folder-with-other-caching-requirements:
            - mdata-name: Cache-Control
              mdata-value: max-age=10000
        - ALL_OBJECTS
            - mdata-name: Content-Language
              mdata-value: en-US
```

I'm happy to work on a PR for this
