### ISSUE TITLE
Reworking documentation

### ISSUE THREAD

**Issue by linusmarco** [fernando-mc/serverless-finch#30]
The current API reference consists of an inline sample yaml file, which works well for the limited set of options available on the current release, but most of the recent PRs add more options, some of which require more complex explanations.

To deal with this, I think we should move towards something more like this for documenting the options:

### bucketName (*required*)

```yaml
custom:
  client:
    bucketName: [unique-s3-bucketname]
```
Use this parameter to specify a unique name for the S3 bucket that your files will be uploaded to.

### distributionFolder (*optional*, defaults to `client/dist`)
```yaml
custom:
  client:
    ...
    distributionFolder: [path/to/files]
```
Use this parameter to specify the path that contains your website files to be uploaded. This path is relative to the path that your `serverless.yaml` configuration files resides in.

etc.

Thoughts?
