### ISSUE TITLE
Doesn't upload at all?

### ISSUE THREAD

**Issue by bebbi** [fernando-mc/serverless-finch#55]
This is a:

* [] Feature request or change
* [x] Bug report

### Expected behavior

Works :)

### Actual behavior

I'm stumped by its behaviour.
bucket is created ok
no files are uploaded into bucket except the CF json
on changing files, says nothing changed.
bucket is private

### Steps to reproduce

Sounds like a strange issue. I reproduce it every time.
On macos, used 2.1.2 with sls 1.27.1 and 1.26.1, and finch 1.4.0 version with 1.27.1

Relevant section in serverless.yml:

```
  client:
    bucketName: ${self:custom.s3Bucket}
    distributionFolder: ./build
    indexDocument: index.html
    errorDocument: index.html
```
Also, I've tried index.html w and w/o paths, ./build or build which is in app package root as expected (it's a monorepo)
There are no other resources in that stage.
Hard to say what happened

* **Operating system:**
* **serverless-finch version:**
* `serverless.yml` **that produces bug:**
* **Command that produces bug:**
* **Other details:**
