### ISSUE TITLE
Deployed bucket cannot be removed from S3

### ISSUE THREAD

**Issue by conanzxn** [fernando-mc/serverless-finch#60]
This is a:

* Bug report

---

For bug reports:

### Expected behavior
The deployed bucket is expected to be removed successfully.

### Actual behavior
The bucket cannot be deleted as the following error outputs.
`ServerlessError: The bucket you tried to delete is not empty`

### Steps to reproduce
`sls client deploy` then `sls client remove`

* **Operating system:** Ubuntu 18.04
* **serverless-finch version:** 3.5.2
* `serverless.yml` **that produces bug:**
```
service: my-bucket-test

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: eu-west-2
  environment:
    LOGGING_LEVEL: DEBUG

  # Give the service full access to the configured notified bucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-bucket-test/*"
package:
  exclude:
    - ./**
  include:
    - ./dist/**

plugins:
  - serverless-finch

custom:
  client:
    bucketName: my-bucket-test
    distributionFolder: ./dist
```

* **Command that produces bug:** `sls client remove`
* **Other details:**
```
Serverless Error ---------------------------------------
 
  ServerlessError: The bucket you tried to delete is not empty
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.27.2
```
