### ISSUE TITLE
Is it possible to deploy/copy files in a certain order

### ISSUE THREAD

**Issue by stefan-lz** [fernando-mc/serverless-finch#63]
Hiya, I would like to be able to deploy files in a certain order, specifically the `index.html` file after all the other assets have been copied over. This will decrease downtime, as all the assets will be resolvable as soon as `index.html` is served.

I've worked around this by deploying using these 2 commands:

```
DIST_FOLDER=build_assets serverless client deploy --no-confirm --no-delete-contents
DIST_FOLDER=build_index serverless client deploy --no-confirm --no-delete-contents
```

with this config:

```
custom:
  client:
    bucketName: ${self:provider.domain}
    distributionFolder: ${env:DIST_FOLDER}
```

Am I missing an easier solution, or could this be better supported in finch?
