### ISSUE TITLE
Doesn't upload to s3, no console output

### ISSUE THREAD

**Issue by jazblueful** [fernando-mc/serverless-finch#74]
This is a:

* [x] Bug report

---

For bug reports:

### Expected behavior
serverless finch tries to upload files from build folder to s3 bucket and serverless outputs something to the console.

### Actual behavior
nothing gets uploaded, there is no output to console.

### Steps to reproduce

* **Operating system:** Ubuntu 18.04
* **serverless-finch version:** 1.3.1
* `serverless.yml` **that produces bug:**
```
service: serverless-graphql-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-bucket-name/*"

plugins:
  - serverless-finch

custom:
  client:
    bucketName: my-bucket-name
    distributionFolder: build
```
* **Command that produces bug:**
sls client deploy
* **Other details:**
I tried to create the bucket myself before running the command, but the result is still the same. I'm running node v9.11.2
---

For feature requests or changes:
