### ISSUE TITLE
client config defined in custom file

### ISSUE THREAD

**Issue by gjimenezv** [fernando-mc/serverless-finch#92]
This is a:
* [x] Bug report

---

**serverless.yml**
`custom: ${file(config.yml)}`

**config.yml**
```
client: 
   bucketName: my-bucket
   errorDocument: index.html
   distributionFolder: build
```
### Expected behavior
Should read client config from custom file
### Actual behavior
Throws and exception 

> TypeError: Cannot read property 'distributionFolder' of undefined at validateClient

### Steps to reproduce

* **Operating system:* Mac OSX 10.14.6 (Mojave)*
* **serverless-finch version:*2.5.2*
* `serverless.yml` **Whatever file with that configuration:**
* **Command that produces bug:*serverless client deploy*
